name: Envio Diario Revenue AI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install pandas fpdf

      - name: Executar Motor
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          echo "--- LISTA DE FICHEIROS ---"
          ls
          echo "--- A EXECUTAR SCRIPT ---"
          python auto_mailer.py
